### PR TITLE
Add BluetoothDevice.forget()

### PR DESCRIPTION
**Pull request by beaufortfrancois**
Similarly to [HIDDevice.forget()](https://chromestatus.com/feature/5723581527883776) and [USBDevice forget()](https://chromestatus.com/feature/5640127995969536), this PR adds BluetoothDevice.forget() so that web developers can revoke permission access to a paired BluetoothDevice.

```js
// Request a Bluetooth device.
const device = await navigator.bluetooth.requestDevice({ acceptAllDevices: true });

// Then later... revoke permission to the Bluetooth device.
await device.forget();
```

@reillyeon Please have a look

***
<a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/pull/574.html" title="Last updated on Apr 11, 2022, 8:34 AM UTC (bea3a26)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WebBluetoothCG/web-bluetooth/574/cecb7f1...bea3a26.html" title="Last updated on Apr 11, 2022, 8:34 AM UTC (bea3a26)">Diff</a>

### CODE REVIEW

**Review by reillyeon — APPROVED** [review]
It looks like you'll need to create an update to how this specification references the Permissions API before this PR can be merged.

**Comment by beaufortfrancois** [comment]
> It looks like you'll need to create an update to how this specification references the Permissions API before this PR can be merged.

I've fixed this by following https://github.com/whatwg/storage/pull/136 example.

**Comment by beaufortfrancois** [comment]
@reillyeon Once https://github.com/WebBluetoothCG/web-bluetooth/pull/576 is merged, this PR should be good to go

**Comment by beaufortfrancois** [comment]
> @reillyeon Once #576 is merged, this PR should be good to go

https://github.com/WebBluetoothCG/web-bluetooth/pull/576 should be merged as well

**Pull request merged**
