### PR TITLE
Use partial interfaces to replace some `implements` statements.

### PR DESCRIPTION
**Pull request by jyasskin**
https://rawgit.com/jyasskin/web-bluetooth-1/partial-interfaces/index.html

@g-ortuno Does this fit in well with your implementation work?

[Review on Reviewable](https://reviewable.io/reviews/webbluetoothcg/web-bluetooth/108)

### CODE REVIEW

**Comment by scheib** [comment]
LGTM, especially fixing #60 is cleaner.

---

Reviewed files:
- index.html @ r1

---





Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/webbluetoothcg/web-bluetooth/108)

**Comment by g-ortuno** [comment]
Implementing a partial interface seems to be more complex that originally thought. We are currently exploring an option to implement the spec as it currently stands.

**Comment by scheib** [comment]
@g-ortuno and I have discussed implementation a bit further, the partial interfaces do have some overhead, perhaps more than just using C++ composition to solve the previous multiple implements version. @g-ortuno will give composition code a shot with multiple implements as that may actually be cleaner, and if so perhaps we shouldn't do this split.

**Comment by jyasskin** [comment]
@g-ortuno @scheib 5e368f09a42aed8660b59a0a9e0e93ded7c4e0fe has the remaining change to extend Navigator with a partial interface instead of using `implements` (now that `BluetoothInteraction` is gone). Let me know if you want this, or if I should just close it.

**Comment by scheib** [comment]
The 'implements' method is simplest to implement in Blink, though both are possible. Choose what feels best for the spec, but if it's a tie stay with 'implements' for impl sake.

**Comment by scheib** [comment]
Sorry, with @g-ortuno reminding me to look closer, Navigator with a partial interface is more consistent in Blink. It is more work for interfaces beyond Navigator to also support being supplemented with partial interfaces, so all other interfaces we'd prefer implements.

**Comment by jyasskin** [comment]
Sounds good. This change now makes only Navigator use a partial interface, with no partial chunks on other interfaces.

**Pull request merged**
