### PR TITLE
Mark sections that are more likely to change.

### PR DESCRIPTION
**Pull request by jyasskin**
These are all unimplemented, and haven't been thought through as well as
the rest of the spec.

Preview at https://api.csswg.org/bikeshed/?url=https://raw.githubusercontent.com/jyasskin/web-bluetooth-1/at-risk/index.bs#permission-api-integration.

### CODE REVIEW

**Comment by g-ortuno** [comment]
What about advertisements?

**Comment by jyasskin** [comment]
I think the `advertisementreceived` event is pretty stable even though we haven't implemented it; do you think it's likely to change?

**Comment by scheib** [comment]
I'd err on the conservative side and mark it not stable if no implementation has started on it.

**Comment by jyasskin** [comment]
Ok, done. Do you think getIncludedService(), descriptors, referringDevice, acceptAllDevices, and Manufacturer/Service data are stable enough even though we haven't started implementing them?

**Comment by jyasskin** [comment]
Ping. I also marked `referringDevice` as unstable, given our difficulties in getting the MAC address from Android.

**Comment by scheib** [comment]
Thanks, I'd use the rule of "if no one has implemented it - then it is unstable". It is the most conservative thing to do, but also sends a clear message about what is easily malleable in the spec.

**Comment by jyasskin** [comment]
Done.

**Pull request merged**
