### PR TITLE
Also fire `gattserverdisconnected` when a page disconnects itself.

### PR DESCRIPTION
**Pull request by jyasskin**
As discussed in #215.

@thegecko

### CODE REVIEW

**Comment by thegecko** [comment]
ack, nice.

**Comment by beaufortfrancois** [comment]
I'll update https://googlechrome.github.io/samples/web-bluetooth/device-disconnect.html as well to remove the `Page is no longer visible...` message then

**Comment by scheib** [comment]
LGTM, with possible additional suggestion of explicitly mentioning that a duplicate event must not arrive when the device is disconnected by the OS.

**Comment by thegecko** [comment]
+1

**Comment by jyasskin** [comment]
@scheib Thanks, done.

**Pull request merged**
