### PR TITLE
Fix #172: Return DataViews instead of ArrayBuffers.

### LINKED ISSUE #172: Returns DataView instead of ArrayBuffer on readValue
I've realized that all the `arrayBuffer` I receive from `readValue` are always wrapped around a `DataView` and I was wondering if we could simply return a `DataView` instead of an `ArrayBuffer` then.

Instead of 

```js
characteristic.readValue().then(buffer => {
  let data = new DataView(buffer);
  let foo = data.getUint8(0);
  ...
```

We would have something simpler like

```js
characteristic.readValue().then(data => {
  let foo = data.getUint8(0);
  // We can always access ArrayBuffer if we need to with data.buffer
  ...

### PR DESCRIPTION
**Pull request by jyasskin**
Preview at https://rawgit.com/jyasskin/web-bluetooth-1/data-view/index.html.

### CODE REVIEW

**Comment by g-ortuno** [comment]
You need to change the examples to use the DataView directly.

**Comment by jyasskin** [comment]
I fixed one last use of `new Uint8Array`, but I think I got everything else. What are you seeing?

**Comment by g-ortuno** [comment]
`parseHeartRate` "`parseHeartRate() would be defined using the heart_rate_measurement documentation to read the ArrayBuffer stored in a BluetoothGATTCharacteristic's value field`" and the code to implement it.

**Comment by jyasskin** [comment]
I got that one. Search https://rawgit.com/jyasskin/web-bluetooth-1/data-view/index.html.

**Comment by g-ortuno** [comment]
Ah my bad. LGTM.

**Comment by beaufortfrancois** [comment]
`s/sensorLocationArray/sensorLocation/g` as it's not an array buffer anymore.

**Comment by jyasskin** [comment]
I went with `sensorLocationData` so it doesn't collide with the variable that was initialized with `let sensorLocation = sensorLocationArray.getUint8(0);`.

**Pull request merged**
