### PR TITLE
Use . instead of @ to refer to internal slots.

### PR DESCRIPTION
**Pull request by jyasskin**
Matches tc39/ecma262#591.

Preview at https://api.csswg.org/bikeshed/?url=https://github.com/jyasskin/web-bluetooth-1/raw/remove-%40/index.bs.

### CODE REVIEW

**Comment by scheib** [comment]
@ -> . LGTM, but I still think that readers will be slightly confused when reading this spec. Perhaps the terms 'Internal Slot' in table headers can link to a simple explanation paragraph (similar to the one you're removing), or the spec sections that state e.g. "Instances of Bluetooth are created with the internal slots described..." could be slightly expanded to explain the internal slot concept.

**Comment by jyasskin** [comment]
I've linked "internal slot" everywhere. Unfortunately, the ES standard is down right now, but I'll ping you when it's back up to check that the target is readable enough.

**Comment by jyasskin** [comment]
https://tc39.github.io/ecma262/#sec-object-internal-methods-and-internal-slots is back.

**Comment by scheib** [comment]
;) The internal slots links are great, thanks.

**Pull request merged**
